/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Calculator_project;

/**
 *
 * @author User
 */
public class Calculator_project extends javax.swing.JFrame {

    /**
     * Creates new form Calculator_project
     */
    public Calculator_project() {
        initComponents();
    }
    String num1="";
    String num2 ="";
    String op = "";
    String res = "";


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        display = new javax.swing.JTextField();
        var2 = new javax.swing.JButton();
        var0 = new javax.swing.JButton();
        var1 = new javax.swing.JButton();
        vardel = new javax.swing.JButton();
        var3 = new javax.swing.JButton();
        var4 = new javax.swing.JButton();
        var7 = new javax.swing.JButton();
        var5 = new javax.swing.JButton();
        var6 = new javax.swing.JButton();
        varclr = new javax.swing.JButton();
        var8 = new javax.swing.JButton();
        var9 = new javax.swing.JButton();
        varmul = new javax.swing.JButton();
        varadd = new javax.swing.JButton();
        varsub = new javax.swing.JButton();
        vardot = new javax.swing.JButton();
        vardiv = new javax.swing.JButton();
        varmod = new javax.swing.JButton();
        vartan = new javax.swing.JButton();
        varsin = new javax.swing.JButton();
        varcos = new javax.swing.JButton();
        varequ = new javax.swing.JButton();
        varsqrt = new javax.swing.JButton();
        varpow = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        display.setFont(new java.awt.Font("Cambria Math", 1, 48)); // NOI18N
        display.setToolTipText("");
        display.setFocusable(false);
        display.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayActionPerformed(evt);
            }
        });

        var2.setFont(new java.awt.Font("Cambria Math", 1, 36)); // NOI18N
        var2.setText("2");
        var2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                var2ActionPerformed(evt);
            }
        });

        var0.setFont(new java.awt.Font("Cambria Math", 1, 36)); // NOI18N
        var0.setText("0");
        var0.setActionCommand("");
        var0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                var0ActionPerformed(evt);
            }
        });

        var1.setFont(new java.awt.Font("Cambria Math", 1, 36)); // NOI18N
        var1.setText("1");
        var1.setActionCommand("");
        var1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                var1ActionPerformed(evt);
            }
        });

        vardel.setFont(new java.awt.Font("Cambria Math", 1, 36)); // NOI18N
        vardel.setText("del");
        vardel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vardelActionPerformed(evt);
            }
        });

        var3.setFont(new java.awt.Font("Cambria Math", 1, 36)); // NOI18N
        var3.setText("3");
        var3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                var3ActionPerformed(evt);
            }
        });

        var4.setFont(new java.awt.Font("Cambria Math", 1, 36)); // NOI18N
        var4.setText("4");
        var4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                var4ActionPerformed(evt);
            }
        });

        var7.setFont(new java.awt.Font("Cambria Math", 1, 36)); // NOI18N
        var7.setText("7");
        var7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                var7ActionPerformed(evt);
            }
        });

        var5.setFont(new java.awt.Font("Cambria Math", 1, 36)); // NOI18N
        var5.setText("5");
        var5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                var5ActionPerformed(evt);
            }
        });

        var6.setFont(new java.awt.Font("Cambria Math", 1, 36)); // NOI18N
        var6.setText("6");
        var6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                var6ActionPerformed(evt);
            }
        });

        varclr.setFont(new java.awt.Font("Cambria Math", 1, 36)); // NOI18N
        varclr.setText("clr");
        varclr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varclrActionPerformed(evt);
            }
        });

        var8.setFont(new java.awt.Font("Cambria Math", 1, 36)); // NOI18N
        var8.setText("8");
        var8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                var8ActionPerformed(evt);
            }
        });

        var9.setFont(new java.awt.Font("Cambria Math", 1, 36)); // NOI18N
        var9.setText("9");
        var9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                var9ActionPerformed(evt);
            }
        });

        varmul.setFont(new java.awt.Font("Cambria Math", 1, 36)); // NOI18N
        varmul.setText("*");
        varmul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varmulActionPerformed(evt);
            }
        });

        varadd.setFont(new java.awt.Font("Cambria Math", 1, 36)); // NOI18N
        varadd.setText("+");
        varadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varaddActionPerformed(evt);
            }
        });

        varsub.setFont(new java.awt.Font("Cambria Math", 1, 36)); // NOI18N
        varsub.setText("-");
        varsub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varsubActionPerformed(evt);
            }
        });

        vardot.setFont(new java.awt.Font("Cambria Math", 1, 36)); // NOI18N
        vardot.setText(".");
        vardot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vardotActionPerformed(evt);
            }
        });

        vardiv.setFont(new java.awt.Font("Cambria Math", 1, 36)); // NOI18N
        vardiv.setText("/");
        vardiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vardivActionPerformed(evt);
            }
        });

        varmod.setFont(new java.awt.Font("Cambria Math", 1, 36)); // NOI18N
        varmod.setText("%");
        varmod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varmodActionPerformed(evt);
            }
        });

        vartan.setFont(new java.awt.Font("Cambria Math", 1, 24)); // NOI18N
        vartan.setText("tan");
        vartan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vartanActionPerformed(evt);
            }
        });

        varsin.setFont(new java.awt.Font("Cambria Math", 1, 24)); // NOI18N
        varsin.setText("sin");
        varsin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varsinActionPerformed(evt);
            }
        });

        varcos.setFont(new java.awt.Font("Cambria Math", 1, 24)); // NOI18N
        varcos.setText("cos");
        varcos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varcosActionPerformed(evt);
            }
        });

        varequ.setFont(new java.awt.Font("Cambria Math", 1, 36)); // NOI18N
        varequ.setText("=");
        varequ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varequActionPerformed(evt);
            }
        });

        varsqrt.setFont(new java.awt.Font("Cambria Math", 1, 36)); // NOI18N
        varsqrt.setText("√");
        varsqrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varsqrtActionPerformed(evt);
            }
        });

        varpow.setFont(new java.awt.Font("Cambria Math", 1, 36)); // NOI18N
        varpow.setText("x²");
        varpow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varpowActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(varsin, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(varcos))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(varadd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(varsub, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(varmul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(vartan, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(varsqrt, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                            .addComponent(vardiv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(varmod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(varpow, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(vardot, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                            .addComponent(varequ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(display)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(var0, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                            .addComponent(var5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(var1, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                            .addComponent(var6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(var7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(var2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(var8, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                            .addComponent(var3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(var4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(vardel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(var9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(varclr, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(display, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(var2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(var4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(vardel, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(var3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(var0, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(var1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(var6, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(var7, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(var5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(var9, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(varclr, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(var8, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(varsub, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(varmul, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(varadd, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(varmod, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vardot, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vardiv, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(varcos, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vartan, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(varsin, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(varpow, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(varequ, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(varsqrt, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EnterNumber(String s) /// it will take input from the display for numbers as a string...
    {
        if(op.equals("²")==true)
        {
            if(num1.length()==0) num1 = s;
            else num1 = num1 + s;
            display.setText("(" +num1 + ")²");
            
        }
        else if(op.equals("sin")==true)
        {
            if(num1.length()==0) num1 = s;
            else num1 = num1 + s;
            display.setText(op + "(" +num1 + ")");
            
        }
        else if(op.equals("cos")==true)
        {
            if(num1.length()==0) num1 = s;
            else num1 = num1 + s;
            display.setText(op + "(" +num1 + ")");
            
        }
        else if(op.equals("tan")==true)
        {
            if(num1.length()==0) num1 = s;
            else num1 = num1 + s;
            display.setText(op + "(" +num1 + ")");
            
        }
        else if(op.equals("√")==true)
        {
            if(num1.length()==0) num1 = s;
            else num1 = num1 + s;
            display.setText(op + num1);
            
        }
        else
        {
            if(op.length()==0)
            {
                if(num1.length()==0) num1 = s;
                else num1 = num1 + s;
                display.setText(num1);
            }
            else if(op.length()>0)
            {
                num2 = num2 + s;
                display.setText(num1+op+num2);
            }
        }
    }

    private void displayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_displayActionPerformed

    private void var2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_var2ActionPerformed
            EnterNumber("2");         // TODO add your handling code here:
    }//GEN-LAST:event_var2ActionPerformed

    private void vardelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vardelActionPerformed
        if(num2.length()>0)
        {
            String box = "";
            for(int i=0 ; i<num2.length()-1 ; i++)
            {
                box = box + num2.charAt(i);
            }
            int index = num2.length();
            
            if(index==1) 
            {
                index = 0;
                num2 = "";
            }
            else
            {
                num2 = box;
                index-=1;
            }
            
            if(index>0 && num2.charAt(index-1)=='.') display.setText(num1 + op + num2 + "0");
            else display.setText(num1 + op + num2);
        }
        else if(op.length()>0 && num1.length()>0 && (op.equals("sin")==true || op.equals("cos")==true || op.equals("tan")==true || op.equals("²")==true || op.equals("√")==true))
        {
            String box = "";
            for(int i=0 ; i<num1.length()-1 ; i++)
            {
                box = box + num1.charAt(i);
            }
            
            int index = num1.length();
            
            if(index==1) 
            {
                index = 0;
                num1 = "";
            }
            else
            {
                num1 = box;
                index-=1;
            }
            
            if(op.equals("√")==true)
            {
                if(index>0 && num1.charAt(index-1)=='.') display.setText("√"+num1 + "0");
                else display.setText("√"+num1);
            }
            else if(op.equals("sin")==true)
            {
                if(index>0 && num1.charAt(index-1)=='.') display.setText("sin("+num1+"0)");
                else display.setText("sin("+num1+")");
            }
            else if(op.equals("tan")==true)
            {
                if(index>0 && num1.charAt(index-1)=='.') display.setText("tan("+num1+"0)");
                else display.setText("tan("+num1+")");
            }
            else if(op.equals("cos")==true)
            {
                if(index>0 && num1.charAt(index-1)=='.') display.setText("cos("+num1+"0)");
                else display.setText("cos("+num1+")");
            }
            else if(op.equals("²")==true)
            {
                if(index>0 && num1.charAt(index-1)=='.') display.setText("("+num1 + "0)²");
                else display.setText("("+num1+")²");
            }
        }
        else if(op.length()>0)
        {
            op = "";
            if(num1.length()>0) display.setText(num1);
            else display.setText("");
        }
        else if(num1.length()>0)
        {
            String box = "";
            for(int i=0 ; i<num1.length()-1 ; i++)
            {
                box = box + num1.charAt(i);
            }
            
            int index = num1.length();
            
            if(index==1) 
            {
                index = 0;
                num1 = "";
            }
            else
            {
                num1 = box;
                index-=1;
            }
            
            if(index>0 && num1.charAt(index-1)=='.') display.setText(num1 + "0");
            else display.setText(num1);
        }

    }//GEN-LAST:event_vardelActionPerformed

    private void var7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_var7ActionPerformed
            EnterNumber("7");         // TODO add your handling code here:
    }//GEN-LAST:event_var7ActionPerformed

    private void varclrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varclrActionPerformed
        num1="";
        num2="";
        op="";
        res = "";
        display.setText("");

    }//GEN-LAST:event_varclrActionPerformed

    private void varmulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varmulActionPerformed
         if(op.length()==0 && num1.length()>0) 
        {
            op = "*";
            display.setText(num1+op);
        }

    }//GEN-LAST:event_varmulActionPerformed

    private void vardotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vardotActionPerformed
               if(op.length()>0 && (op.equals("sin")==true || op.equals("cos")==true || op.equals("tan")==true || op.equals("²")==true || op.equals("√")==true))
        {
            if(num1.contains(".")==false) 
            {
                if(num1.length()==0) num1="0.";
                else num1 = num1 + ".";
                
                if(op.equals("√")==true)
                {
                    display.setText("√"+num1);
                }
                else if(op.equals("sin")==true)
                {
                    display.setText("sin("+num1+")");
                }
                else if(op.equals("tan")==true)
                {
                    display.setText("tan("+num1+")");
                }
                else if(op.equals("cos")==true)
                {
                    display.setText("cos("+num1+")");
                }
                else if(op.equals("²")==true)
                {
                    display.setText("("+num1 + ")²");
                }
            }
            
        }
        else if(op.length()>0)
        {
            if(num2.contains(".")==false)
            {
                if(num2.length()>0) num2 = num2 + ".";
                else num2 = "0.";
                display.setText(num1 + op + num2);
            }
        }
        else if(num1.contains(".")==false && op.length()==0)
        {
            if(num1.length()==0) num1 = "0.";
            else num1 = num1 + ".";
            display.setText(num1);
        }
    }//GEN-LAST:event_vardotActionPerformed

    private void vartanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vartanActionPerformed
        if(num1.length()==0 && op.length()==0)
        {
            op="tan";
            display.setText(op);
        }
        else if(op.length()==0)
        {
            op="tan";
            display.setText(op+"("+num1+")");
        }

    }//GEN-LAST:event_vartanActionPerformed

    private void varequActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varequActionPerformed
        if(op.equals("+")==true)
        {
            Double x = Double.parseDouble(num1);
            Double y = Double.parseDouble(num2);
            x = x + y;
            res = x + "";
            int pos = -1;
            String box = "";
            for(int i=0 ; i<res.length() ; i++)
            {
                if(res.charAt(i)=='.')
                {
                    pos = i+1;
                    break;
                }
                box = box + res.charAt(i);
            }
            int f = 0;
            for(int i=pos ; i<res.length() ; i++)
            {
                if(res.charAt(i)!='0')
                {
                    f++;
                    break;
                }
            }
            
            if(f==0) res = box;
            if(res.equals("INT")==true || res.equals("MATH ERROR")==true ) num1="";
            else num1 = res;
            num2 = "";
            op = "";
            display.setText(res);
        }
        else if(op.equals("-")==true)
        {
            Double x = Double.parseDouble(num1);
            Double y = Double.parseDouble(num2);
            x = x - y;
            res = x + "";
            int pos = -1;
            String box = "";
            for(int i=0 ; i<res.length() ; i++)
            {
                if(res.charAt(i)=='.')
                {
                    pos = i+1;
                    break;
                }
                box = box + res.charAt(i);
            }
            int f = 0;
            for(int i=pos ; i<res.length() ; i++)
            {
                if(res.charAt(i)!='0')
                {
                    f++;
                    break;
                }
            }
            if(f==0) res = box;
            if(res.equals("INT")==true || res.equals("MATH ERROR")==true ) num1="";
            else num1 = res;
            num2 = "";
            op = "";
            display.setText(res);
        }
        else if(op.equals("*")==true)
        {
            Double x = Double.parseDouble(num1);
            Double y = Double.parseDouble(num2);
            x = x * y;
            res = x + "";
            int pos = -1;
            String box = "";
            for(int i=0 ; i<res.length() ; i++)
            {
                if(res.charAt(i)=='.')
                {
                    pos = i+1;
                    break;
                }
                box = box + res.charAt(i);
            }
            int f = 0;
            for(int i=pos ; i<res.length() ; i++)
            {
                if(res.charAt(i)!='0')
                {
                    f++;
                    break;
                }
            }
            
            if(f==0) res = box;
            if(res.equals("INT")==true || res.equals("MATH ERROR")==true ) num1="";
            else num1 = res;
            num2 = "";
            op = "";
            display.setText(res);
        }
        else if(op.equals("%")==true)
        {
            Double x = Double.parseDouble(num1);
            Double y = Double.parseDouble(num2);
            if(y>0) x = x % y;
            
            res = x + "";
            if(y==0) res = "MATH ERROR";
            int pos = -1;
            String box = "";
            if(y!=0)
            {
                for(int i=0 ; i<res.length() ; i++)
                {
                    if(res.charAt(i)=='.')
                    {
                        pos = i+1;
                        break;
                    }
                    box = box + res.charAt(i);
                }
                int f = 0;
                for(int i=pos ; i<res.length() ; i++)
                {
                    if(res.charAt(i)!='0')
                    {
                        f++;
                        break;
                    }
                }

                if(f==0) res = box;
            }
            
            if(res.equals("INT")==true || res.equals("MATH ERROR")==true ) num1="";
            else num1 = res;
            num2 = "";
            op = "";
            display.setText(res);
        }
        else if(op.equals("/")==true)
        {
            Double x = Double.parseDouble(num1);
            Double y = Double.parseDouble(num2);
            if(y>0) x = x / y;
            
            res = x + "";
            if(y==0) res = "INF";
            int pos = -1;
            String box = "";
            int f = 0;
            if(y!=0)
            {
                for(int i=0 ; i<res.length() ; i++)
                {
                    if(res.charAt(i)=='.')
                    {
                        pos = i+1;
                        break;
                    }
                    box = box + res.charAt(i);
                }
                
                for(int i=pos ; i<res.length() ; i++)
                {
                    if(res.charAt(i)!='0')
                    {
                        f++;
                        break;
                    }
                }
                if(f==0) res = box;
            }
            
            if(res.equals("INT")==true || res.equals("MATH ERROR")==true ) num1="";
            else num1 = res;
            num2 = "";
            op = "";
            display.setText(res);
        }
        else if(op.equals("√")==true)
        {
            Double x = Double.parseDouble(num1);
            
            if(x<0)
            {
                res = "MATH ERROR";
            }
            else
            {
                x = Math.sqrt(x);
                res = x + "";
                int pos = -1;
                String box = "";
                for(int i=0 ; i<res.length() ; i++)
                {
                    if(res.charAt(i)=='.')
                    {
                        pos = i+1;
                        break;
                    }
                    box = box + res.charAt(i);
                }
                int f = 0;
                for(int i=pos ; i<res.length() ; i++)
                {
                    if(res.charAt(i)!='0')
                    {
                        f++;
                        break;
                    }
                }

                if(f==0) res = box;
            }
            
            if(res.equals("INT")==true || res.equals("MATH ERROR")==true ) num1="";
            else num1 = res;
            num2 = "";
            op = "";
            display.setText(res);
        }
        else if(op.equals("²")==true)
        {
            Double x = Double.parseDouble(num1);
            x = Math.pow(x,2);
            res = x + "";
            int pos = -1;
            String box = "";
            for(int i=0 ; i<res.length() ; i++)
            {
                if(res.charAt(i)=='.')
                {
                    pos = i+1;
                    break;
                }
                box = box + res.charAt(i);
            }
            int f = 0;
            for(int i=pos ; i<res.length() ; i++)
            {
                if(res.charAt(i)!='0')
                {
                    f++;
                    break;
                }
            }
            
            if(f==0) res = box;
            if(res.equals("INT")==true || res.equals("MATH ERROR")==true ) num1="";
            else num1 = res;
            num2 = "";
            op = "";
            display.setText(res);
        }
        else if(op.equals("sin")==true)
        {
            Double x = Double.parseDouble(num1);
            x = Math.sin(x);
            res = x + "";
            int pos = -1;
            String box = "";
            for(int i=0 ; i<res.length() ; i++)
            {
                if(res.charAt(i)=='.')
                {
                    pos = i+1;
                    break;
                }
                box = box + res.charAt(i);
            }
            int f = 0;
            for(int i=pos ; i<res.length() ; i++)
            {
                if(res.charAt(i)!='0')
                {
                    f++;
                    break;
                }
            }
            
            if(f==0) res = box;
            if(res.equals("INT")==true || res.equals("MATH ERROR")==true ) num1="";
            else num1 = res;
            num2 = "";
            op = "";
            display.setText(res);
        }
        else if(op.equals("cos")==true)
        {
            Double x = Double.parseDouble(num1);
            x = Math.cos(x);
            res = x + "";
            int pos = -1;
            String box = "";
            for(int i=0 ; i<res.length() ; i++)
            {
                if(res.charAt(i)=='.')
                {
                    pos = i+1;
                    break;
                }
                box = box + res.charAt(i);
            }
            int f = 0;
            for(int i=pos ; i<res.length() ; i++)
            {
                if(res.charAt(i)!='0')
                {
                    f++;
                    break;
                }
            }
            
            if(f==0) res = box;
            if(res.equals("INT")==true || res.equals("MATH ERROR")==true ) num1="";
            else num1 = res;
            num2 = "";
            op = "";
            display.setText(res);
        }
        else if(op.equals("tan")==true)
        {
            Double x = Double.parseDouble(num1);
            if(x!=90) x = Math.tan(x);
            else res = "INF";
            
            int pos = -1;
            String box = "";
            if(x!=90)
            {
                res = x + "";
                for(int i=0 ; i<res.length() ; i++)
                {
                    if(res.charAt(i)=='.')
                    {
                        pos = i+1;
                        break;
                    }
                    box = box + res.charAt(i);
                }
                int f = 0;
                for(int i=pos ; i<res.length() ; i++)
                {
                    if(res.charAt(i)!='0')
                    {
                        f++;
                        break;
                    }
                }

                if(f==0) res = box;
            }
            if(res.equals("INT")==true || res.equals("MATH ERROR")==true ) num1="";
            else num1 = res;
            num2 = "";
            op = "";
            display.setText(res);
        }
        

    }//GEN-LAST:event_varequActionPerformed

    private void var0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_var0ActionPerformed
            EnterNumber("0");         // TODO add your handling code here:
    }//GEN-LAST:event_var0ActionPerformed

    private void vardivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vardivActionPerformed
        if(op.length()==0 && num1.length()>0) 
        {
            op = "/";
            display.setText(num1+op);
        }

    }//GEN-LAST:event_vardivActionPerformed

    private void var1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_var1ActionPerformed
            EnterNumber("1");         // TODO add your handling code here:
    }//GEN-LAST:event_var1ActionPerformed

    private void var3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_var3ActionPerformed
            EnterNumber("3");         // TODO add your handling code here:
    }//GEN-LAST:event_var3ActionPerformed

    private void var4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_var4ActionPerformed
            EnterNumber("4");         // TODO add your handling code here:
    }//GEN-LAST:event_var4ActionPerformed

    private void var5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_var5ActionPerformed
            EnterNumber("5");         // TODO add your handling code here:
    }//GEN-LAST:event_var5ActionPerformed

    private void var6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_var6ActionPerformed
            EnterNumber("6");         // TODO add your handling code here:
    }//GEN-LAST:event_var6ActionPerformed

    private void var8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_var8ActionPerformed
            EnterNumber("8");         // TODO add your handling code here:
    }//GEN-LAST:event_var8ActionPerformed

    private void var9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_var9ActionPerformed
            EnterNumber("9");         // TODO add your handling code here:
    }//GEN-LAST:event_var9ActionPerformed

    private void varaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varaddActionPerformed
        if(op.length()==0 && num1.length()>0) 
        {
            op = "+";
            display.setText(num1+op);
        }

    }//GEN-LAST:event_varaddActionPerformed

    private void varsubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varsubActionPerformed
        if(op.length()==0 && num1.length()>0) 
        {
            op = "-";
            display.setText(num1+op);
        }

    }//GEN-LAST:event_varsubActionPerformed

    private void varsqrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varsqrtActionPerformed
         if(num1.length()==0 && op.length()==0)
        {
            op="√";
            display.setText(op);
        }
        else if(op.length()==0)
        {
            op="√";
            display.setText(op+num1);
        }

    }//GEN-LAST:event_varsqrtActionPerformed

    private void varsinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varsinActionPerformed
        if(num1.length()==0 && op.length()==0)
        {
            op="sin";
            display.setText(op);
        }
        else if(op.length()==0)
        {
            op="sin";
            display.setText(op+"("+num1+")");
        }

    }//GEN-LAST:event_varsinActionPerformed

    private void varcosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varcosActionPerformed
        if(num1.length()==0 && op.length()==0)
        {
            op="cos";
            display.setText(op);
        }
        else if(op.length()==0)
        {
            op="cos";
            display.setText(op+"("+num1+")");
        }
    }//GEN-LAST:event_varcosActionPerformed

    private void varpowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varpowActionPerformed
        if(num1.length()==0 && op.length()==0)
        {
            op="²";
            display.setText("()"+op);
        }
        else if(op.length()==0)
        {
            op="²";
            display.setText("("+num1+")"+op);
        }

    }//GEN-LAST:event_varpowActionPerformed

    private void varmodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varmodActionPerformed
        if(op.length()==0 && num1.length()>0) 
        {
            op = "%";
            display.setText(num1+op);
        }

    }//GEN-LAST:event_varmodActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator_project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator_project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator_project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator_project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator_project().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField display;
    private javax.swing.JButton var0;
    private javax.swing.JButton var1;
    private javax.swing.JButton var2;
    private javax.swing.JButton var3;
    private javax.swing.JButton var4;
    private javax.swing.JButton var5;
    private javax.swing.JButton var6;
    private javax.swing.JButton var7;
    private javax.swing.JButton var8;
    private javax.swing.JButton var9;
    private javax.swing.JButton varadd;
    private javax.swing.JButton varclr;
    private javax.swing.JButton varcos;
    private javax.swing.JButton vardel;
    private javax.swing.JButton vardiv;
    private javax.swing.JButton vardot;
    private javax.swing.JButton varequ;
    private javax.swing.JButton varmod;
    private javax.swing.JButton varmul;
    private javax.swing.JButton varpow;
    private javax.swing.JButton varsin;
    private javax.swing.JButton varsqrt;
    private javax.swing.JButton varsub;
    private javax.swing.JButton vartan;
    // End of variables declaration//GEN-END:variables
}
